name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/tp4-cicd:latest
        docker build -t $IMAGE .
        echo "Built image $IMAGE"

    - name: Push image to Docker Hub
      run: |
        IMAGE=${{ secrets.DOCKER_USERNAME }}/tp4-cicd:latest
        docker push $IMAGE
